version: "3"

services:
  ml_promobot:
    image: kvadimas/foodgram_backend
    restart: always
    env_file: .env
    expose:
      - "9000:9000"
    container_name: ml_promobot

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ml_promobot
