# -*- coding: utf-8 -*-
"""NER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vyx_jYyoRUxos6MRf9_CT9Y1afPlFPY_
"""

#!python -m spacy download ru_core_news_lg
import spacy
import ru_core_news_lg

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words("russian")
from nltk.tokenize import word_tokenize
nltk.download('punkt')

nlp = ru_core_news_lg.load()
stop_words = list(stopwords.words("russian"))
stop_words.extend(['Сообщение', 'Текста', 'Текст', 'Здравствуйте', 'Хотел', 'Подтверждаю', 'Добрый', 'День','начать', 'Доброе', 'Утро', 'Вечер', 'Скажите', 'Пожалуйста', 'Сегодня', 'Подскажите', '""', 'Конструкторы', 'Какаие', 'Могу', 'Заранее', 'Прошу', 'Поставьте', 'Устроили', 'Планирую'])


def get_location(message):
    text = nlp(message)
    return str(text.ents)
